<?php

// Auto-generated by bin/migrate — do not edit manually.
// Generated:      2026-03-15 21:02:48 (development)
// Last migration: 0007_posts_unique_title.php

return [

    'api_keys' => [
        'id'         => ['type' => 'char(36)', 'nullable' => false, 'default' => null , 'extra' => null ],
        'name'       => ['type' => 'varchar(255)', 'nullable' => false, 'default' => null , 'extra' => null ],
        'token'      => ['type' => 'char(64)', 'nullable' => false, 'default' => null , 'extra' => null ],
        'created_at' => ['type' => 'timestamp', 'nullable' => true , 'default' => 'current_timestamp()', 'extra' => null ],
    ],

    'contacts' => [
        'id'         => ['type' => 'char(36)', 'nullable' => false, 'default' => null , 'extra' => null ],
        'email'      => ['type' => 'varchar(255)', 'nullable' => false, 'default' => null , 'extra' => null ],
        'message'    => ['type' => 'text', 'nullable' => false, 'default' => null , 'extra' => null ],
        'created_at' => ['type' => 'timestamp', 'nullable' => true , 'default' => 'current_timestamp()', 'extra' => null ],
    ],

    'posts' => [
        'id'         => ['type' => 'char(36)', 'nullable' => false, 'default' => null , 'extra' => null ],
        'title'      => ['type' => 'varchar(255)', 'nullable' => false, 'default' => null , 'extra' => null ],
        'body'       => ['type' => 'text', 'nullable' => true , 'default' => 'NULL', 'extra' => null ],
        'created_at' => ['type' => 'timestamp', 'nullable' => true , 'default' => 'current_timestamp()', 'extra' => null ],
        'updated_at' => ['type' => 'timestamp', 'nullable' => true , 'default' => 'current_timestamp()', 'extra' => 'on update current_timestamp()'],
    ],

    'subscribers' => [
        'id'         => ['type' => 'char(36)', 'nullable' => false, 'default' => null , 'extra' => null ],
        'email'      => ['type' => 'varchar(255)', 'nullable' => false, 'default' => null , 'extra' => null ],
        'created_at' => ['type' => 'timestamp', 'nullable' => true , 'default' => 'current_timestamp()', 'extra' => null ],
    ],

    'users' => [
        'id'              => ['type' => 'char(36)', 'nullable' => false, 'default' => null , 'extra' => null ],
        'email'           => ['type' => 'varchar(255)', 'nullable' => false, 'default' => null , 'extra' => null ],
        'password_digest' => ['type' => 'varchar(255)', 'nullable' => false, 'default' => null , 'extra' => null ],
        'role'            => ['type' => 'varchar(50)', 'nullable' => false, 'default' => 'admin', 'extra' => null ],
        'created_at'      => ['type' => 'timestamp', 'nullable' => true , 'default' => 'current_timestamp()', 'extra' => null ],
    ],

];
